---
# tasks file for roles/mtail

- name: "Add service group {{ mtail_service_group }}"
  group:
    name: "{{ mtail_service_group }}"
    gid: "{{ mtail_service_gid }}"
    state: present
    system: yes
    non_unique: no

- name: "Add service user {{ mtail_service_user }}"
  user:
    name: "{{ mtail_service_user }}"
    comment: "system user for service {{ mtail_service_name }}"
    uid: "{{ mtail_service_uid }}"
    group: "{{ mtail_service_group }}"
    shell: "/usr/sbin/nologin"
    state: present
    system: yes
    createhome: no
    non_unique: no
    home: "{{ mtail_progs }}"

- name: "Install mtail"
  include_tasks: "install_{{ mtail_install_method.get(ansible_lsb.id, 'download') }}.yml"

- name: "Create progs directory"
  file:
    path: "{{ mtail_progs }}"
    state: directory
    owner: "root"
    group: "{{ mtail_service_group }}"
    mode: 0o0750
  notify:
    - "restart {{ mtail_service_name }}"

- name: "Create log directory"
  file:
    path: "{{ mtail_logdir }}"
    state: directory
    owner: "{{ mtail_service_user }}"
    group: root
    mode: 0o0750
  when: mtail_logdir|bool
  notify:
    - "restart {{ mtail_service_name }}"

- name: "Grant {{ mtail_service_user }} read access to log files"
  acl:
    state: present
    path: "{{ item }}"
    entity: "{{ mtail_service_user }}"
    etype: user
    permissions: r
  with_items: "{{ mtail_logs }}"
  notify:
    - "restart mtail"

- name: "Install systemd unit file for mtail"
  template:
    src: "{{ mtail_service_name }}.service.j2"
    dest: "/etc/systemd/system/{{ mtail_service_name }}.service"
    owner: root
    group: root
    mode: 0o0644
  notify:
    - "restart {{ mtail_service_name }}"
  when: ansible_service_mgr == "systemd"
  register: mtail_unit

- name: "Install AppArmor profile"
  template:
    src: "apparmor-mtail.j2"
    dest: "/etc/apparmor.d/{{ mtail_apparmor_profile }}"
    owner: root
    group: root
    mode: 0o0644
  notify:
    - "restart apparmor"
    - "restart {{ mtail_service_name }}"
  when: mtail_apparmor_enabled == True

- name: "Make sure systemd unit files are reloaded"
  systemd:
    daemon_reload: yes
  when: ansible_service_mgr == "systemd" and mtail_unit.changed

- name: "Enable and start service {{ mtail_service_name }}"
  service:
    name: "{{ mtail_service_name }}"
    state: started
    enabled: yes
