---
# handlers file for roles/mtail

- name: "reload apparmor"
  listen:
    - "restart apparmor"
  service:
    name: "apparmor"
    state: restarted

- name: "restart mtail"
  listen:
    - "restart mtail"
  service:
    name: "{{ mtail_service_name }}"
    state: restarted
